### ISSUE TITLE
Issue with Comparison operators

### ISSUE THREAD

**Issue by MartyOfMCA** [sanskaarz/LearnJS#11]
**Issue Description**
Under the section [Comparison Operators](https://github.com/sanskaarz/LearnJS?tab=readme-ov-file#comparison-operators) the first item on the list is not a valid comparison operator. I understand you explained its purpose as an assignment operator but for clarity, kindly remove it from the section of comparison operators. Thanks!

**Comment by sanskaarz** [comment]
could you please raise a PR
